### ISSUE TITLE
Wrong slash commands branch git URL in FAQ

### ISSUE THREAD

**Issue by laundmo** [Pycord-Development/robocord#1]
The bot currently gives this command to install pycord with slash commands:

```
pip install git+https://github.com/Pycord-Development/pycord@slash
```
![](https://img.laundmo.com/u/D2oRWx.png)

This points at the wrong branch, as the branch is actually called `feature/slash`
![](https://img.laundmo.com/u/ZoT0ri.png)

The correct url is `pip install git+https://github.com/Pycord-Development/pycord@feature/slash`
![](https://img.laundmo.com/u/PNAxYj.png)

**Comment by BobDotCom** [comment]
this issue is with a different bot, but when the code from that bot is merged into this one, it will be resolved.
